### ISSUE TITLE
Use UTF-8 for Cyrillic messages

### ISSUE THREAD

**Issue by rfdrew** [wk-tech/python-smsfly#13]
```
*** smsfly.py   2017-01-29 02:59:07.967282733 +0200
--- smsfly_utf.py       2016-10-29 06:08:21.000000000 +0300
***************
*** 23,28 ****
--- 23,29 ----
      @parse_xml_response
      def __request(self, request_xml_body):
          req_body = str(request_xml_body)
+         req_body = req_body.encode("utf-8")
          logger.debug('Submitting POST request to SMS-Fly API {}.\nRequest body: {}'.
                       format(self.API_URL, req_body))
          return self.__http.post(self.API_URL, data=req_body)

```

**Comment by webknjaz** [comment]
?

**Comment by rfdrew** [comment]
При отправке кириллических сообщений получаем такую ошибку.
```
  File "/usr/lib/python3.4/http/client.py", line 1127, in _send_request
    body = body.encode('iso-8859-1')
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 187-190: ordinal not in range(256)
```
Решается добавлением body.encode('utf-8')

PS^ Возможно решается на уровне python скрипта, но я не нашел как.

**Comment by webknjaz** [comment]
я якби на 3.5+ орієнтувався. а взагалі, [приймаються PR](https://github.com/open-craft-guild/python-smsfly/compare), а не шматки патчів.
щодо кодування, то ймовірно можна в requests.post типове задати. крім того, там же на вхід приходить юнікод, кодувати його в байти не бачу сенсу

**Comment by webknjaz** [comment]
поки лишу повний трейс тут для подальшого розбору пізніше:
```python
$ vagga manage.py smsfly_query --api-method=send-sms --sms-text='Привіт світ!' --sms-recipient='+380123456789' -v3
SMS-Fly API wrapper has been initialized
Submitting POST request to SMS-Fly API http://sms-fly.com/api/api.php.
Request body: <?xml version="1.0" encoding="utf-8"?>
<request><operation>SENDSMS</operation><message desc="Sending SMS from django command by @webknjaz" end_time="AUTO" lifetime="24" rate="120" source="InfoCentr" start_time="AUTO"><body>Привіт світ!</body><recipient>+380123456789</recipient></message></request>
Starting new HTTP connection (1): sms-fly.com
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3.5/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3.5/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python3.5/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python3.5/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/work/SMSFlyCRM/SMSApp/management/commands/smsfly_query.py", line 44, in handle
    api_result = getattr(self.smsfly_api, api_method_name)(**api_kwargs)
  File "/work/src/smsfly/src/smsfly/smsfly.py", line 40, in send_sms_to_recipient
    message_pairs=((recipient, body), ), individual_mode=False)
  File "/work/src/smsfly/src/smsfly/smsfly.py", line 72, in __sendsms
    return self.__request(xml_req)
  File "/work/src/smsfly/src/smsfly/util.py", line 32, in wrapper
    res_text = f(*args, **kwargs).text
  File "/work/src/smsfly/src/smsfly/smsfly.py", line 28, in __request
    return self.__http.post(self.API_URL, data=req_body)
  File "/usr/lib/python3.5/site-packages/requests/sessions.py", line 535, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3.5/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.5/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.5/site-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 356, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.5/http/client.py", line 1083, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1127, in _send_request
    body = body.encode('iso-8859-1')
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 223-228: ordinal not in range(256)
```

**Comment by webknjaz** [comment]
The root of issue is that requests forget's to encode string into bytes as required by urllib3. Still it encodes body in case of rendering `json`:  https://github.com/kennethreitz/requests/blob/fae3f92c34d8d7267de33ecb676b3d5600146257/requests/models.py#L463

**Comment by webknjaz** [comment]
@rfdrew 
https://pypi.python.org/pypi/SMSFly <-- зарелізив 0.1.4
